---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: ui-agi-wheezy-budgerigar
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: ui
  namespace: ui-agi-wheezy-budgerigar
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: bfe9c18e5e0dd9bb90050fc43cd5cd8a994e1625
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: agi-wheezy-budgerigar
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-52e8bb3b1f7963f8d0f5c3a49db142bf1c199fdd
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: api-agi-wheezy-budgerigar
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-354-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: api
  namespace: api-agi-wheezy-budgerigar
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: agi-wheezy-budgerigar
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-354-merge-fb06217e4f80b7e0d1813ac82ae4ff10384695ce
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: worker-agi-wheezy-budgerigar
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: worker
  namespace: worker-agi-wheezy-budgerigar
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: fc236f47f4c511c7629bae0bf69eaa0fe284c274
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: agi-wheezy-budgerigar
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: pipeline-agi-wheezy-budgerigar
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: agi-wheezy-budgerigar
  name: pipeline
  namespace: pipeline-agi-wheezy-budgerigar
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 7ff5726e5e35e10a1a1a35c95f8b1e9cc17bd6e6
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-7ff5726e5e35e10a1a1a35c95f8b1e9cc17bd6e6-pipeline-runner
    replicaCount: 0
    sandboxId: agi-wheezy-budgerigar
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
