---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-gamy-booby
  name: ui-ahriman-gamy-booby
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-gamy-booby
  name: ui
  namespace: ui-ahriman-gamy-booby
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: d680d14d32e946591c02293f6f931a750b65f678
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ahriman-gamy-booby
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-dbaafef951d6c1d0e078046c3598522503443e01
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-gamy-booby
  name: api-ahriman-gamy-booby
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-gamy-booby
  name: api
  namespace: api-ahriman-gamy-booby
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: d680d14d32e946591c02293f6f931a750b65f678
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: ahriman-gamy-booby
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-16c436ad1098d9e47a0e103cbda30cb6966d0fed
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-gamy-booby
  name: worker-ahriman-gamy-booby
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-gamy-booby
  name: worker
  namespace: worker-ahriman-gamy-booby
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: fc236f47f4c511c7629bae0bf69eaa0fe284c274
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ahriman-gamy-booby
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-gamy-booby
  name: pipeline-ahriman-gamy-booby
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-239-merge-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ahriman-gamy-booby
  name: pipeline
  namespace: pipeline-ahriman-gamy-booby
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: refs/pull/239/head
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 29Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-239-merge-cbd3e04b3a30ef09c6e145874bcc30dfc98710f3-pipeline-runner
    replicaCount: 0
    sandboxId: ahriman-gamy-booby
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
