---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: ui-ahriman-lumpy-tuatara
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: ui
  namespace: ui-ahriman-lumpy-tuatara
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 77fae7669761c14a051b34585b7151478f85174c
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ahriman-lumpy-tuatara
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-a6cc6e39b448a2443b6a22aff4078c9b12b0af56
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: api-ahriman-lumpy-tuatara
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-335-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: api
  namespace: api-ahriman-lumpy-tuatara
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: ahriman-lumpy-tuatara
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-335-merge-bac558c1eea4fa61a2e4728b74a4d0f67d23c38e
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: worker-ahriman-lumpy-tuatara
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: worker
  namespace: worker-ahriman-lumpy-tuatara
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: 6a1d82f5abbefe8344062dbf94970beea48df359
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-6a1d82f5abbefe8344062dbf94970beea48df359-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-6a1d82f5abbefe8344062dbf94970beea48df359-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ahriman-lumpy-tuatara
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: pipeline-ahriman-lumpy-tuatara
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ahriman-lumpy-tuatara
  name: pipeline
  namespace: pipeline-ahriman-lumpy-tuatara
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: afdfd942f10bd89e49f5aa282fc3136699ec9d95
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 29Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-270c7c320fab7e1020fdb21df09170059eb70c92-pipeline-runner
    replicaCount: 0
    sandboxId: ahriman-lumpy-tuatara
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
