apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: ui-ivababukova-gloppy-okapi
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-712-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: ui
  namespace: ui-ivababukova-gloppy-okapi
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: ivababukova-gloppy-okapi
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-pull-712-merge-b6f9a7e5d815996c475add9a9eea727082866e8d
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: ui-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: api-ivababukova-gloppy-okapi
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: api
  namespace: api-ivababukova-gloppy-okapi
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 9699725758a1d468b60b550280b0b1e2ea5dbb4a
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: STAGING_RDS_SANDBOX_ID
      repo: hms-dbmi-cellenics/api
      sandboxId: ivababukova-gloppy-okapi
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-16c436ad1098d9e47a0e103cbda30cb6966d0fed
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: api-role-staging
  valuesFrom:
  - configMapKeyRef:
      key: account-config.yaml
      name: account-config
      namespace: flux
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: worker-ivababukova-gloppy-okapi
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: worker
  namespace: worker-ivababukova-gloppy-okapi
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: fc236f47f4c511c7629bae0bf69eaa0fe284c274
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-fc236f47f4c511c7629bae0bf69eaa0fe284c274-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: ivababukova-gloppy-okapi
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: pipeline-ivababukova-gloppy-okapi
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: ivababukova-gloppy-okapi
  name: pipeline
  namespace: pipeline-ivababukova-gloppy-okapi
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 1a6cc8006ec454638b949aebc7764a64e164f261
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-1a6cc8006ec454638b949aebc7764a64e164f261-pipeline-runner
    replicaCount: 0
    sandboxId: ivababukova-gloppy-okapi
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
