apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: martinfosco-api347
  name: ui-martinfosco-api347
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: martinfosco-api347
  name: ui
  namespace: ui-martinfosco-api347
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: b34b41aa7a502a408e7386c280c89da6962446e3
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: martinfosco-api347
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-c7c21e17f2adf808305a3110ca8f582985d2776a
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: martinfosco-api347
  name: api-martinfosco-api347
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-pull-347-merge-*
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: martinfosco-api347
  name: api
  namespace: api-martinfosco-api347
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: refs/heads/master
  releaseName: api
  values:
    biomageCi:
      rdsSandboxId: default
      repo: hms-dbmi-cellenics/api
      sandboxId: martinfosco-api347
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-347-merge-4cbd550a619b7de2efc7d65911a77edc903c0eac
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: martinfosco-api347
  name: worker-martinfosco-api347
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-heads-master-*-python
    filter.fluxcd.io/r: glob:refs-heads-master-*-r
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: martinfosco-api347
  name: worker
  namespace: worker-martinfosco-api347
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: 333ad3e21df3d0bf730ae93a61c41a68e2a554d7
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-333ad3e21df3d0bf730ae93a61c41a68e2a554d7-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-333ad3e21df3d0bf730ae93a61c41a68e2a554d7-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: martinfosco-api347
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: martinfosco-api347
  name: pipeline-martinfosco-api347
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: martinfosco-api347
  name: pipeline
  namespace: pipeline-martinfosco-api347
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 09990887c01e75bbd2566264c93c682373940c7a
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-09990887c01e75bbd2566264c93c682373940c7a-pipeline-runner
    replicaCount: 0
    sandboxId: martinfosco-api347
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
