---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: olivergibson-worker248
  name: ui-olivergibson-worker248
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: olivergibson-worker248
  name: ui
  namespace: ui-olivergibson-worker248
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 57a14b10e9ab022aa3788b19fd53af90f08a1dba
  releaseName: ui
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: olivergibson-worker248
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-384eb501bc4fe46e5b6f164f21c25a810f5cb040
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    loadBalancerHealthCheck:
      path: /robots.txt
      periodSeconds: 30
    readinessProbe:
      command:
      - echo
      - '0'
      probeType: exec
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: olivergibson-worker248
  name: api-olivergibson-worker248
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: olivergibson-worker248
  name: api
  namespace: api-olivergibson-worker248
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: 57a14b10e9ab022aa3788b19fd53af90f08a1dba
  releaseName: api
  values:
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: olivergibson-worker248
    hpa:
      enabled: false
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-heads-master-b357f3875a61d237714fc23cdb22777267a73ad1
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    livenessProbe:
      probeType: tcpSocket
    readinessProbe:
      path: /v1/health
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
    service:
      externalPort: 3000
      internalPort: 3000
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: olivergibson-worker248
  name: worker-olivergibson-worker248
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/python: glob:refs-pull-248-merge-*-python
    filter.fluxcd.io/r: glob:refs-pull-248-merge-*-r
    fluxcd.io/automated: 'true'
  labels:
    sandboxId: olivergibson-worker248
  name: worker
  namespace: worker-olivergibson-worker248
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/worker
    path: chart-infra/
    ref: refs/pull/248/head
  releaseName: worker
  values:
    kubernetes:
      env: staging
    python:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-248-merge-77cc517d9322b808f267aa6ce4d707eca684060a-python
    r:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-248-merge-77cc517d9322b808f267aa6ce4d707eca684060a-r
      memoryRequest: 4Gi
    replicaCount: 0
    sandboxId: olivergibson-worker248
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/worker-role-staging
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    sandboxId: olivergibson-worker248
  name: pipeline-olivergibson-worker248
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    filter.fluxcd.io/pipelineRunner: glob:refs-heads-master-*-pipeline-runner
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    fluxcd.io/automated: 'false'
  labels:
    sandboxId: olivergibson-worker248
  name: pipeline
  namespace: pipeline-olivergibson-worker248
spec:
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: c9fb5d5213dbb275237b1ba1769f15faeee8e43a
  releaseName: pipeline
  values:
    awsAccountId: '242905224710'
    awsRegion: eu-west-1
    clusterEnv: staging
    memoryRequest: 4Gi
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-heads-master-c9fb5d5213dbb275237b1ba1769f15faeee8e43a-pipeline-runner
    replicaCount: 0
    sandboxId: olivergibson-worker248
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
