apiVersion: v1
kind: Namespace
metadata:
  name: ui-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ui
  namespace: ui-default
  labels:
    sandboxId: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-heads-master-*
spec:
  releaseName: ui
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: master
  values:
    # disable readiness probes as load balancer performs
    # its own health checks/cordoning
    readinessProbe:
      probeType: exec
      command: ["echo", "0"]
    loadBalancerHealthCheck:
      path: "/robots.txt"
      periodSeconds: 30
    livenessProbe:
      probeType: tcpSocket
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/ui
      sandboxId: default
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: ui
      tag: refs-heads-master-b7b03c407e3f33f5de671b471f6fb2f208f7fa26
    replicaCount: 4
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/ui-role-staging

# filled in by CI. do not modify.
