apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-default
  labels:
    sandboxId: default
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/pipelineRunner: glob:refs-tags-*-pipeline-runner
  labels:
    sandboxId: default
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: 270c7c320fab7e1020fdb21df09170059eb70c92
  values:
    clusterEnv: production
    awsAccountId: "242905224710"
    awsRegion: eu-west-1
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-tags-0.16.0-pipeline-runner
    sandboxId: default
    memoryRequest: 29Gi
    replicaCount: 3
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-production
