apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/remoter-server: FILLED_IN_BY_CI
    filter.fluxcd.io/remoter-client: FILLED_IN_BY_CI
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-225-merge-*-pipeline-runner
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: STAGING_CHART_REF
  values:
    clusterEnv: staging
    awsAccountId: "242905224710"
    awsRegion: eu-west-1
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-225-merge-71d2b6073fcb63e6f58d1b11118b088f4f206713-pipeline-runner
    sandboxId: STAGING_SANDBOX_ID
    memoryRequest: 4Gi
    replicaCount: 0
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/pipeline-role-staging
