apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: pipeline
  namespace: pipeline-STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/pipelineRunner: glob:refs-pull-249-merge-*-pipeline-runner
  labels:
    sandboxId: STAGING_SANDBOX_ID
spec:
  releaseName: pipeline
  chart:
    git: git@github.com:hms-dbmi-cellenics/pipeline
    path: chart-infra/
    ref: STAGING_CHART_REF
  valuesFrom:
    - configMapKeyRef:
        name: account-config
        namespace: flux
        key: account-config.yaml
  values:
    clusterEnv: staging
    pipelineRunner:
      image: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/pipeline:refs-pull-249-merge-b7644752e103277090885b234a746f3916525dc0-pipeline-runner
    sandboxId: STAGING_SANDBOX_ID
    memoryRequest: 29Gi
    replicaCount: 0
    serviceAccount:
      iamRole: pipeline-role-staging
