apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-runner
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ template "serviceAccountRole" . }}
    sandboxId: "{{ .Values.biomageCi.sandboxId }}"