apiVersion: v1
kind: Namespace
metadata:
  name: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: api-STAGING_SANDBOX_ID
  labels:
    sandboxId: STAGING_SANDBOX_ID
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:refs-pull-301-merge-*
spec:
  releaseName: api
  chart:
    git: git@github.com:hms-dbmi-cellenics/iac
    path: charts/nodejs
    ref: STAGING_CHART_REF
  values:
    service:
      externalPort: 3000
      internalPort: 3000
    readinessProbe:
      path: "/v1/health"
    livenessProbe:
      probeType: tcpSocket
    resources:
      requests:
        cpu: "100m"
    hpa:
      enabled: false
    ingress:
      annotations:
        alb.ingress.kubernetes.io/healthcheck-path: /v1/health
    kubernetes:
      env: staging
    biomageCi:
      repo: hms-dbmi-cellenics/api
      sandboxId: STAGING_SANDBOX_ID
    image:
      registry: 242905224710.dkr.ecr.eu-west-1.amazonaws.com
      repository: api
      tag: refs-pull-301-merge-49985e2cc162f9dbea81c01e629f0dcfea7499bc
    replicaCount: 1
    serviceAccount:
      iamRole: arn:aws:iam::242905224710:role/api-role-staging

# filled in by CI. do not modify.
