name: Sync Fork

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          # token: ${{ secrets.API_TOKEN_GITHUB }}
          owner: hms-dbmi-cellenics
          base: master
          head: master